export const pass_data = [
  {
    title: "GitHub",
    link: "https://github.com",
    email: "bhavik@gmail.com",
    pass: "123456",
  },
  {
    title: "Google",
    link: "https://google.com",
    email: "bhavik@gmail.com",
    pass: "google@123",
  },
  {
    title: "LinkedIn",
    link: "https://linkedin.com",
    email: "bhavik@gmail.com",
    pass: "linkedin@123",
  },
  {
    title: "Instagram",
    link: "https://instagram.com",
    email: "bhavik@gmail.com",
    pass: "insta@123",
  },
  {
    title: "Netflix",
    link: "https://netflix.com",
    email: "bhavik@gmail.com",
    pass: "netflix@123",
  },
  {
    title: "Vercel",
    link: "https://vercel.com",
    email: "bhavik@gmail.com",
    pass: "vrc_secure$99",
  },
  {
    title: "Spotify",
    link: "https://spotify.com",
    email: "bhavik@gmail.com",
    pass: "musicLover!8",
  },
  {
    title: "Amazon",
    link: "https://amazon.com",
    email: "bhavik@gmail.com",
    pass: "amzn_shop#2026",
  },
  {
    title: "Figma",
    link: "https://figma.com",
    email: "bhavik@gmail.com",
    pass: "design_vector%4",
  },
  {
    title: "Twitter / X",
    link: "https://x.com",
    email: "bhavik@gmail.com",
    pass: "tweet_blue_90",
  },
  {
    title: "Stack Overflow",
    link: "https://stackoverflow.com",
    email: "bhavik@gmail.com",
    pass: "ctrl+c_ctrl+v",
  },
  {
    title: "Discord",
    link: "https://discord.com",
    email: "bhavik@gmail.com",
    pass: "gamers_unite_77",
  },
  {
    title: "Notion",
    link: "https://notion.so",
    email: "bhavik@gmail.com",
    pass: "notes_workspace_2",
  },
  {
    title: "Adobe Creative Cloud",
    link: "https://adobe.com",
    email: "bhavik@gmail.com",
    pass: "photoshop_cc_26",
  },
  {
    title: "Microsoft 365",
    link: "https://microsoft.com",
    email: "bhavik@gmail.com",
    pass: "outlook_office_5",
  },
  {
    title: "Airbnb",
    link: "https://airbnb.com",
    email: "bhavik@gmail.com",
    pass: "travel_stay_2026",
  },
  {
    title: "Pinterest",
    link: "https://pinterest.com",
    email: "bhavik@gmail.com",
    pass: "moodboard_pin_8",
  },
  {
    title: "Twitch",
    link: "https://twitch.tv",
    email: "bhavik@gmail.com",
    pass: "stream_live_44",
  },
  {
    title: "Canva",
    link: "https://canva.com",
    email: "bhavik@gmail.com",
    pass: "easy_design_101",
  },
  {
    title: "Medium",
    link: "https://medium.com",
    email: "bhavik@gmail.com",
    pass: "writer_blog_99",
  },
];
